---
devices :
 - hostname : "cc23-s-361"
   ip :  "10.126.142.2"
   role : "access switch"
   type : switch

 - hostname : "cc23-s-362" 
   ip : "10.126.142.3"
   role : "access switch"
   type: switch

 - hostname : "cc23-s-363" 
   ip : "10.126.142.10"
   role : "access switch"
   type : switch

 - hostname : "cc23-s-364" 
   ip : "10.126.142.11"
   name : "oss switch"
   type : switch

 - hostname : "cc23-s-064"
   ip :  "10.126.142.4"
   name : "oss switch"
   type : switch

 - hostname : "cc23-s-065"
   ip : "10.126.142.5"
   name : "oss switch"
   type : switch

 - hostname : "cc23-s-066"
   ip : "10.126.142.12"
   name : "oss switch"
   type : switch

 - hostname : "cc23-s-067" 
   ip : "10.126.142.13"
   name : "oss switch"
   type : switch

 - hostname : "cc23-s-861" 
   ip : "10.126.145.100"
   role : "aggregation switch"
   type : switch

 - hostname : "cc23-s-862"
   ip : "10.126.145.101"
   role : "aggregation switch"
   type : switch

 - hostname : "cc23-s-863"
   ip : "10.126.145.102"
   role : "aggregation switch"
   type : switch

 - hostname : "cc23-s-864"
   ip : "10.126.145.103"
   role : "aggregation switch"
   type : switch

 - hostname : "c4b3-s-861"
   ip : "10.126.145.117"
   role : "aggregation switch"
   type : switch

 - hostname : "c4b3-s-862"
   ip :  "10.126.145.118"
   role : "aggregation switch"
   type : switch

